// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbtiy4e2qT7QLG0qW21X0DCTqjnIS1bE',
    appId: '1:334137481464:android:300b1f812c711071bd830d',
    messagingSenderId: '334137481464',
    projectId: 'fir-practice-743d2',
    databaseURL: 'https://fir-practice-743d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-743d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChWxecF8tjAaRJJ9IFszM53ufgPjz_MM',
    appId: '1:334137481464:ios:927ca455a205671abd830d',
    messagingSenderId: '334137481464',
    projectId: 'fir-practice-743d2',
    databaseURL: 'https://fir-practice-743d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-743d2.appspot.com',
    androidClientId: '334137481464-7hlhop9okeg39k27ij4adqkrrogqnr3p.apps.googleusercontent.com',
    iosClientId: '334137481464-qdr7t73hgv0dbn0ro4vnjb5sae4hcqke.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapplication',
  );
}
